# Generated by Django 5.1.2 on 2024-10-28 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40, unique=True)),
                ('company_gstno', models.CharField(max_length=15, unique=True)),
                ('createdby', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=8)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('adhaar_number', models.CharField(max_length=12, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_company', to='employee.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='attachments/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attachments', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(choices=[('10th class', '10TH CLASS'), ('12th class', '12TH CLASS'), ('b.tech', 'B.TECH'), ('m.tech', 'M.TECH'), ('mca', 'MCA'), ('bca', 'BCA')], default='10th class', max_length=20)),
                ('college_name', models.CharField(max_length=50)),
                ('college_location', models.CharField(max_length=40)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_educations', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carry_forward', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='employee.company')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTypeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavename', models.CharField(max_length=50)),
                ('leave_description', models.TextField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='employee.company')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_days', models.IntegerField()),
                ('carry_forward_type', models.CharField(choices=[('monthly', 'MONTHLY'), ('quarterly', 'QUARTERLY')], default='monthly', max_length=10)),
                ('leave_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_types', to='employee.leavepolicy')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policy_types', to='employee.leavetypeindex')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeavesRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('leave_day_type', models.CharField(choices=[('Full day', 'Full day'), ('Half day (1st half)', 'Half day (1st half)'), ('Half day (2nd half)', 'Half day (2nd half)')], default='Full day', max_length=20)),
                ('reporting_manager_email', models.EmailField(max_length=254)),
                ('reason_for_leave', models.TextField()),
                ('status_of_leave', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.leavetypeindex')),
            ],
        ),
    ]
